# Generated by Django 4.2 on 2024-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
    ]
