# Generated by Django 4.2 on 2024-05-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='infor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10.34, max_digits=4),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='salary',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
