# Generated by Django 4.2 on 2024-05-07 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_usermodel_infor_usermodel_money_usermodel_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default='2005-03-04'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birthday2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birthday3',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
