# Generated by Django 4.2 on 2024-05-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_usermodel_birthday_usermodel_birthday2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='icon',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
