# Generated by Django 4.2 on 2024-05-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_usermodel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='icon2',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
