# Generated by Django 4.2 on 2024-05-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_usermodel_icon2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type2',
            field=models.IntegerField(db_column='utype2', default=1, editable=False, verbose_name='用户类型2'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='utype',
            field=models.IntegerField(choices=[(1, '青铜'), (2, '白银'), (3, '黄金')], default=1, verbose_name='用户类型'),
        ),
    ]
