# Generated by Django 4.2 on 2024-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_usermodel_icon_alter_usermodel_icon2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField(default=18)),
            ],
            options={
                'db_table': 'tb_person',
            },
        ),
    ]
